id: P009081
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 19:21:57.435025
source_metadata:
  id: bdr:W19472
  title: བརྟག་པ་གཉིས་པའི་འགྲེལ་པ་རིན་ཆེན་རྒྱན་འདྲ
  author: ''
  volumes:
    7b8be7e7855a436daeb99c172ca93518:
      image_group_id: I00KG03882
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
