id: P009081
initial_creation_type: ocr
source_metadata:
  id: bdr:W19472
  title: བརྟག་པ་གཉིས་པའི་འགྲེལ་པ་རིན་ཆེན་རྒྱན་འདྲ
  author: ''
  volumes:
    7b8be7e7855a436daeb99c172ca93518:
      image_group_id: I00KG03882
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
